outfile: 'results/result_voice.mp4'
static: False
fps: 25
pads: [0, 10, 0, 0]
face_det_batch_size: 16
wav2lip_batch_size: 128
resize_factor: 1
crop: [0, -1, 0, -1]
box: [-1, -1, -1, -1]
rotate: False
nosmooth: False
img_size: 96